// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"github.com/gofiber/fiber/v2"
	"github.com/yourusername/wemake/api"
)

// Injectors from wire.go:

// InitializeApp initializes and returns the Fiber application with all dependencies
// Wire will auto-generate the dependency graph at compile time
func InitializeApp() (*fiber.App, error) {
	config := provideConfig()
	db := provideDatabase(config)
	app := api.SetupRoutes(db, config)
	return app, nil
}
